[book]
authors = ["realtradam"]
language = "en"
multilingual = false
src = "src"
title = "Ice Is Nice"

[build]
create-missing = false

[output.html.fold]
enable = true
level = 1

[output.html]
default-theme = "rust"
preferred-dark-theme = "rust"

[output.html.search]
enable = true
